### ISSUE TITLE
An issue with tracemoepy

### ISSUE THREAD

**Issue by thehyperpineapple** [xjl98/AniPy-Bot#1]
I was unable to run pip install -r requirements.txt so i manually attempted to install tracemoepy but it was outputted as an error. Is there any reason for this?

**Comment by CoastalPrince** [comment]
Yeah, i faced the same issue  with this command pip install -r requirements.txt.What's exactly the problem here and how to fix it ?

**Comment by JackLikesHotpot** [comment]
Just to confirm, but do either of you have pip installed? 
I used pip version 19.3.1 to download the packages. 
Works for me and a friend.

**Comment by thehyperpineapple** [comment]
Yes I do. I have pip version 20.2.2

**Comment by JackLikesHotpot** [comment]
I'm not entirely sure why it's like this but alternatively, you could try `pip3 install -r requirements.txt`.

Even if it doesn't work, you should be able to download it directly [here](https://pypi.org/project/tracemoepy/). 
If the above doesn't work, do you mind taking a screenshot of the error?
